// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/common.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_ERROR_NONE               ErrorCode = 0 // No error
	ErrorCode_ERROR_NOT_FOUND          ErrorCode = 1 // Generic not found (queue, namespace, etc.)
	ErrorCode_ERROR_UNAUTHORIZED       ErrorCode = 2 // Access denied
	ErrorCode_ERROR_INTERNAL           ErrorCode = 3 // Internal server error
	ErrorCode_ERROR_QUEUE_DISABLED     ErrorCode = 4 // Queue exists but is disabled
	ErrorCode_ERROR_SHARD_UNHEALTHY    ErrorCode = 5 // Target shard unavailable or unhealthy
	ErrorCode_ERROR_TIMEOUT            ErrorCode = 6 // Request timed out
	ErrorCode_ERROR_INVALID_ARGUMENT   ErrorCode = 7 // Malformed or missing request data
	ErrorCode_ERROR_DEPENDENCY_FAILURE ErrorCode = 8 // Downstream system (e.g., storage, network) failed
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_NONE",
		1: "ERROR_NOT_FOUND",
		2: "ERROR_UNAUTHORIZED",
		3: "ERROR_INTERNAL",
		4: "ERROR_QUEUE_DISABLED",
		5: "ERROR_SHARD_UNHEALTHY",
		6: "ERROR_TIMEOUT",
		7: "ERROR_INVALID_ARGUMENT",
		8: "ERROR_DEPENDENCY_FAILURE",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_NONE":               0,
		"ERROR_NOT_FOUND":          1,
		"ERROR_UNAUTHORIZED":       2,
		"ERROR_INTERNAL":           3,
		"ERROR_QUEUE_DISABLED":     4,
		"ERROR_SHARD_UNHEALTHY":    5,
		"ERROR_TIMEOUT":            6,
		"ERROR_INVALID_ARGUMENT":   7,
		"ERROR_DEPENDENCY_FAILURE": 8,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_proto_common_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{0}
}

type FailureReason int32

const (
	FailureReason_MESSAGE_FAILURE_UNSPECIFIED FailureReason = 0  // Default/unset
	FailureReason_HANDLER_TIMEOUT             FailureReason = 1  // Handler exceeded execution time
	FailureReason_MAX_RETRY_EXCEEDED          FailureReason = 2  // Retry count exceeded
	FailureReason_INVALID_PAYLOAD             FailureReason = 3  // Message body or format is bad
	FailureReason_PROCESSING_ERROR            FailureReason = 4  // Uncaught error during handler
	FailureReason_EXPIRED                     FailureReason = 5  // TTL expired before processing
	FailureReason_POISON_MESSAGE              FailureReason = 6  // Message caused repeated crashes
	FailureReason_UNAUTHORIZED_HANDLER        FailureReason = 7  // Handler rejected due to auth
	FailureReason_QUEUE_NOT_FOUND             FailureReason = 8  // Queue missing at processing time
	FailureReason_DROPPED_DUE_TO_SHUTDOWN     FailureReason = 9  // Message lost during node shutdown
	FailureReason_VISIBILITY_TIMEOUT_EXCEEDED FailureReason = 10 // Lock expired before ack or renew
)

// Enum value maps for FailureReason.
var (
	FailureReason_name = map[int32]string{
		0:  "MESSAGE_FAILURE_UNSPECIFIED",
		1:  "HANDLER_TIMEOUT",
		2:  "MAX_RETRY_EXCEEDED",
		3:  "INVALID_PAYLOAD",
		4:  "PROCESSING_ERROR",
		5:  "EXPIRED",
		6:  "POISON_MESSAGE",
		7:  "UNAUTHORIZED_HANDLER",
		8:  "QUEUE_NOT_FOUND",
		9:  "DROPPED_DUE_TO_SHUTDOWN",
		10: "VISIBILITY_TIMEOUT_EXCEEDED",
	}
	FailureReason_value = map[string]int32{
		"MESSAGE_FAILURE_UNSPECIFIED": 0,
		"HANDLER_TIMEOUT":             1,
		"MAX_RETRY_EXCEEDED":          2,
		"INVALID_PAYLOAD":             3,
		"PROCESSING_ERROR":            4,
		"EXPIRED":                     5,
		"POISON_MESSAGE":              6,
		"UNAUTHORIZED_HANDLER":        7,
		"QUEUE_NOT_FOUND":             8,
		"DROPPED_DUE_TO_SHUTDOWN":     9,
		"VISIBILITY_TIMEOUT_EXCEEDED": 10,
	}
)

func (x FailureReason) Enum() *FailureReason {
	p := new(FailureReason)
	*p = x
	return p
}

func (x FailureReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailureReason) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_proto_enumTypes[1].Descriptor()
}

func (FailureReason) Type() protoreflect.EnumType {
	return &file_proto_common_proto_enumTypes[1]
}

func (x FailureReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailureReason.Descriptor instead.
func (FailureReason) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{1}
}

// Generic status response for any RPC call
type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         ErrorCode              `protobuf:"varint,2,opt,name=error,proto3,enum=proto.ErrorCode" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{0}
}

func (x *StatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StatusResponse) GetError() ErrorCode {
	if x != nil {
		return x.Error
	}
	return ErrorCode_ERROR_NONE
}

type KokaqStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         map[string]uint64      `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Status        *StatusResponse        `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KokaqStatsResponse) Reset() {
	*x = KokaqStatsResponse{}
	mi := &file_proto_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KokaqStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KokaqStatsResponse) ProtoMessage() {}

func (x *KokaqStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KokaqStatsResponse.ProtoReflect.Descriptor instead.
func (*KokaqStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{1}
}

func (x *KokaqStatsResponse) GetStats() map[string]uint64 {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *KokaqStatsResponse) GetStatus() *StatusResponse {
	if x != nil {
		return x.Status
	}
	return nil
}

type KokaqNamespaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KokaqNamespaceRequest) Reset() {
	*x = KokaqNamespaceRequest{}
	mi := &file_proto_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KokaqNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KokaqNamespaceRequest) ProtoMessage() {}

func (x *KokaqNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KokaqNamespaceRequest.ProtoReflect.Descriptor instead.
func (*KokaqNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{2}
}

func (x *KokaqNamespaceRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type KokaqNamespaceResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Namespace       string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TotalQueueCount uint64                 `protobuf:"varint,2,opt,name=total_queue_count,json=totalQueueCount,proto3" json:"total_queue_count,omitempty"`
	CreatedOn       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_on,json=createdOn,proto3" json:"created_on,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *KokaqNamespaceResponse) Reset() {
	*x = KokaqNamespaceResponse{}
	mi := &file_proto_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KokaqNamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KokaqNamespaceResponse) ProtoMessage() {}

func (x *KokaqNamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KokaqNamespaceResponse.ProtoReflect.Descriptor instead.
func (*KokaqNamespaceResponse) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{3}
}

func (x *KokaqNamespaceResponse) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *KokaqNamespaceResponse) GetTotalQueueCount() uint64 {
	if x != nil {
		return x.TotalQueueCount
	}
	return 0
}

func (x *KokaqNamespaceResponse) GetCreatedOn() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedOn
	}
	return nil
}

type KokaqQueueRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Queue                    string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	Namespace                string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	CreatedOn                *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_on,json=createdOn,proto3" json:"created_on,omitempty"`
	DefaultExpiry            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=default_expiry,json=defaultExpiry,proto3" json:"default_expiry,omitempty"`
	DefaultVisibilityTimeout uint32                 `protobuf:"varint,5,opt,name=default_visibility_timeout,json=defaultVisibilityTimeout,proto3" json:"default_visibility_timeout,omitempty"`
	MaxDequeueCount          uint32                 `protobuf:"varint,6,opt,name=max_dequeue_count,json=maxDequeueCount,proto3" json:"max_dequeue_count,omitempty"`
	MaxPriority              uint64                 `protobuf:"varint,7,opt,name=max_priority,json=maxPriority,proto3" json:"max_priority,omitempty"`
	MinPriority              uint64                 `protobuf:"varint,8,opt,name=min_priority,json=minPriority,proto3" json:"min_priority,omitempty"`
	EnableDeadLetter         bool                   `protobuf:"varint,9,opt,name=enable_dead_letter,json=enableDeadLetter,proto3" json:"enable_dead_letter,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *KokaqQueueRequest) Reset() {
	*x = KokaqQueueRequest{}
	mi := &file_proto_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KokaqQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KokaqQueueRequest) ProtoMessage() {}

func (x *KokaqQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KokaqQueueRequest.ProtoReflect.Descriptor instead.
func (*KokaqQueueRequest) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{4}
}

func (x *KokaqQueueRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *KokaqQueueRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *KokaqQueueRequest) GetCreatedOn() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedOn
	}
	return nil
}

func (x *KokaqQueueRequest) GetDefaultExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.DefaultExpiry
	}
	return nil
}

func (x *KokaqQueueRequest) GetDefaultVisibilityTimeout() uint32 {
	if x != nil {
		return x.DefaultVisibilityTimeout
	}
	return 0
}

func (x *KokaqQueueRequest) GetMaxDequeueCount() uint32 {
	if x != nil {
		return x.MaxDequeueCount
	}
	return 0
}

func (x *KokaqQueueRequest) GetMaxPriority() uint64 {
	if x != nil {
		return x.MaxPriority
	}
	return 0
}

func (x *KokaqQueueRequest) GetMinPriority() uint64 {
	if x != nil {
		return x.MinPriority
	}
	return 0
}

func (x *KokaqQueueRequest) GetEnableDeadLetter() bool {
	if x != nil {
		return x.EnableDeadLetter
	}
	return false
}

type KokaqQueueResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Request        *KokaqQueueRequest     `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	ShardId        uint64                 `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	TotalNodeCount uint64                 `protobuf:"varint,3,opt,name=total_node_count,json=totalNodeCount,proto3" json:"total_node_count,omitempty"`
	TotalPageCount uint64                 `protobuf:"varint,4,opt,name=total_page_count,json=totalPageCount,proto3" json:"total_page_count,omitempty"`
	CreatedOn      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_on,json=createdOn,proto3" json:"created_on,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KokaqQueueResponse) Reset() {
	*x = KokaqQueueResponse{}
	mi := &file_proto_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KokaqQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KokaqQueueResponse) ProtoMessage() {}

func (x *KokaqQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KokaqQueueResponse.ProtoReflect.Descriptor instead.
func (*KokaqQueueResponse) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{5}
}

func (x *KokaqQueueResponse) GetRequest() *KokaqQueueRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *KokaqQueueResponse) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *KokaqQueueResponse) GetTotalNodeCount() uint64 {
	if x != nil {
		return x.TotalNodeCount
	}
	return 0
}

func (x *KokaqQueueResponse) GetTotalPageCount() uint64 {
	if x != nil {
		return x.TotalPageCount
	}
	return 0
}

func (x *KokaqQueueResponse) GetCreatedOn() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedOn
	}
	return nil
}

var File_proto_common_proto protoreflect.FileDescriptor

const file_proto_common_proto_rawDesc = "" +
	"\n" +
	"\x12proto/common.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"R\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12&\n" +
	"\x05error\x18\x02 \x01(\x0e2\x10.proto.ErrorCodeR\x05error\"\xb9\x01\n" +
	"\x12KokaqStatsResponse\x12:\n" +
	"\x05stats\x18\x01 \x03(\v2$.proto.KokaqStatsResponse.StatsEntryR\x05stats\x12-\n" +
	"\x06status\x18\x02 \x01(\v2\x15.proto.StatusResponseR\x06status\x1a8\n" +
	"\n" +
	"StatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"5\n" +
	"\x15KokaqNamespaceRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\"\x9d\x01\n" +
	"\x16KokaqNamespaceResponse\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12*\n" +
	"\x11total_queue_count\x18\x02 \x01(\x04R\x0ftotalQueueCount\x129\n" +
	"\n" +
	"created_on\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedOn\"\xa3\x03\n" +
	"\x11KokaqQueueRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x129\n" +
	"\n" +
	"created_on\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedOn\x12A\n" +
	"\x0edefault_expiry\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rdefaultExpiry\x12<\n" +
	"\x1adefault_visibility_timeout\x18\x05 \x01(\rR\x18defaultVisibilityTimeout\x12*\n" +
	"\x11max_dequeue_count\x18\x06 \x01(\rR\x0fmaxDequeueCount\x12!\n" +
	"\fmax_priority\x18\a \x01(\x04R\vmaxPriority\x12!\n" +
	"\fmin_priority\x18\b \x01(\x04R\vminPriority\x12,\n" +
	"\x12enable_dead_letter\x18\t \x01(\bR\x10enableDeadLetter\"\xf2\x01\n" +
	"\x12KokaqQueueResponse\x122\n" +
	"\arequest\x18\x01 \x01(\v2\x18.proto.KokaqQueueRequestR\arequest\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\x04R\ashardId\x12(\n" +
	"\x10total_node_count\x18\x03 \x01(\x04R\x0etotalNodeCount\x12(\n" +
	"\x10total_page_count\x18\x04 \x01(\x04R\x0etotalPageCount\x129\n" +
	"\n" +
	"created_on\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedOn*\xde\x01\n" +
	"\tErrorCode\x12\x0e\n" +
	"\n" +
	"ERROR_NONE\x10\x00\x12\x13\n" +
	"\x0fERROR_NOT_FOUND\x10\x01\x12\x16\n" +
	"\x12ERROR_UNAUTHORIZED\x10\x02\x12\x12\n" +
	"\x0eERROR_INTERNAL\x10\x03\x12\x18\n" +
	"\x14ERROR_QUEUE_DISABLED\x10\x04\x12\x19\n" +
	"\x15ERROR_SHARD_UNHEALTHY\x10\x05\x12\x11\n" +
	"\rERROR_TIMEOUT\x10\x06\x12\x1a\n" +
	"\x16ERROR_INVALID_ARGUMENT\x10\a\x12\x1c\n" +
	"\x18ERROR_DEPENDENCY_FAILURE\x10\b*\x96\x02\n" +
	"\rFailureReason\x12\x1f\n" +
	"\x1bMESSAGE_FAILURE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fHANDLER_TIMEOUT\x10\x01\x12\x16\n" +
	"\x12MAX_RETRY_EXCEEDED\x10\x02\x12\x13\n" +
	"\x0fINVALID_PAYLOAD\x10\x03\x12\x14\n" +
	"\x10PROCESSING_ERROR\x10\x04\x12\v\n" +
	"\aEXPIRED\x10\x05\x12\x12\n" +
	"\x0ePOISON_MESSAGE\x10\x06\x12\x18\n" +
	"\x14UNAUTHORIZED_HANDLER\x10\a\x12\x13\n" +
	"\x0fQUEUE_NOT_FOUND\x10\b\x12\x1b\n" +
	"\x17DROPPED_DUE_TO_SHUTDOWN\x10\t\x12\x1f\n" +
	"\x1bVISIBILITY_TIMEOUT_EXCEEDED\x10\n" +
	"B!Z\x1fgithub.com/kokaq/protocol/protob\x06proto3"

var (
	file_proto_common_proto_rawDescOnce sync.Once
	file_proto_common_proto_rawDescData []byte
)

func file_proto_common_proto_rawDescGZIP() []byte {
	file_proto_common_proto_rawDescOnce.Do(func() {
		file_proto_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_common_proto_rawDesc), len(file_proto_common_proto_rawDesc)))
	})
	return file_proto_common_proto_rawDescData
}

var file_proto_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_common_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_common_proto_goTypes = []any{
	(ErrorCode)(0),                 // 0: proto.ErrorCode
	(FailureReason)(0),             // 1: proto.FailureReason
	(*StatusResponse)(nil),         // 2: proto.StatusResponse
	(*KokaqStatsResponse)(nil),     // 3: proto.KokaqStatsResponse
	(*KokaqNamespaceRequest)(nil),  // 4: proto.KokaqNamespaceRequest
	(*KokaqNamespaceResponse)(nil), // 5: proto.KokaqNamespaceResponse
	(*KokaqQueueRequest)(nil),      // 6: proto.KokaqQueueRequest
	(*KokaqQueueResponse)(nil),     // 7: proto.KokaqQueueResponse
	nil,                            // 8: proto.KokaqStatsResponse.StatsEntry
	(*timestamppb.Timestamp)(nil),  // 9: google.protobuf.Timestamp
}
var file_proto_common_proto_depIdxs = []int32{
	0, // 0: proto.StatusResponse.error:type_name -> proto.ErrorCode
	8, // 1: proto.KokaqStatsResponse.stats:type_name -> proto.KokaqStatsResponse.StatsEntry
	2, // 2: proto.KokaqStatsResponse.status:type_name -> proto.StatusResponse
	9, // 3: proto.KokaqNamespaceResponse.created_on:type_name -> google.protobuf.Timestamp
	9, // 4: proto.KokaqQueueRequest.created_on:type_name -> google.protobuf.Timestamp
	9, // 5: proto.KokaqQueueRequest.default_expiry:type_name -> google.protobuf.Timestamp
	6, // 6: proto.KokaqQueueResponse.request:type_name -> proto.KokaqQueueRequest
	9, // 7: proto.KokaqQueueResponse.created_on:type_name -> google.protobuf.Timestamp
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_common_proto_init() }
func file_proto_common_proto_init() {
	if File_proto_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_common_proto_rawDesc), len(file_proto_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_proto_goTypes,
		DependencyIndexes: file_proto_common_proto_depIdxs,
		EnumInfos:         file_proto_common_proto_enumTypes,
		MessageInfos:      file_proto_common_proto_msgTypes,
	}.Build()
	File_proto_common_proto = out.File
	file_proto_common_proto_goTypes = nil
	file_proto_common_proto_depIdxs = nil
}
