// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/control.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDataplaneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Queue         string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataplaneRequest) Reset() {
	*x = GetDataplaneRequest{}
	mi := &file_proto_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataplaneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataplaneRequest) ProtoMessage() {}

func (x *GetDataplaneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataplaneRequest.ProtoReflect.Descriptor instead.
func (*GetDataplaneRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{0}
}

func (x *GetDataplaneRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetDataplaneRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

type GetDataplaneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Queue         string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataplaneResponse) Reset() {
	*x = GetDataplaneResponse{}
	mi := &file_proto_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataplaneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataplaneResponse) ProtoMessage() {}

func (x *GetDataplaneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataplaneResponse.ProtoReflect.Descriptor instead.
func (*GetDataplaneResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{1}
}

func (x *GetDataplaneResponse) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetDataplaneResponse) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *GetDataplaneResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_proto_control_proto protoreflect.FileDescriptor

const file_proto_control_proto_rawDesc = "" +
	"\n" +
	"\x13proto/control.proto\x12\x05proto\x1a\x12proto/common.proto\"I\n" +
	"\x13GetDataplaneRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\"d\n" +
	"\x14GetDataplaneResponse\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress2\x84\x05\n" +
	"\x11KokaqControlPlane\x12G\n" +
	"\fGetDataplane\x12\x1a.proto.GetDataplaneRequest\x1a\x1b.proto.GetDataplaneResponse\x12K\n" +
	"\fGetNamespace\x12\x1c.proto.KokaqNamespaceRequest\x1a\x1d.proto.KokaqNamespaceResponse\x12K\n" +
	"\fAddNamespace\x12\x1c.proto.KokaqNamespaceRequest\x1a\x1d.proto.KokaqNamespaceResponse\x12F\n" +
	"\x0fDeleteNamespace\x12\x1c.proto.KokaqNamespaceRequest\x1a\x15.proto.StatusResponse\x12?\n" +
	"\bAddQueue\x12\x18.proto.KokaqQueueRequest\x1a\x19.proto.KokaqQueueResponse\x12?\n" +
	"\bGetQueue\x12\x18.proto.KokaqQueueRequest\x1a\x19.proto.KokaqQueueResponse\x12>\n" +
	"\vDeleteQueue\x12\x18.proto.KokaqQueueRequest\x1a\x15.proto.StatusResponse\x12=\n" +
	"\n" +
	"ClearQueue\x12\x18.proto.KokaqQueueRequest\x1a\x15.proto.StatusResponse\x12C\n" +
	"\bGetStats\x12\x1c.proto.KokaqNamespaceRequest\x1a\x19.proto.KokaqStatsResponseB!Z\x1fgithub.com/kokaq/protocol/protob\x06proto3"

var (
	file_proto_control_proto_rawDescOnce sync.Once
	file_proto_control_proto_rawDescData []byte
)

func file_proto_control_proto_rawDescGZIP() []byte {
	file_proto_control_proto_rawDescOnce.Do(func() {
		file_proto_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_control_proto_rawDesc), len(file_proto_control_proto_rawDesc)))
	})
	return file_proto_control_proto_rawDescData
}

var file_proto_control_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_control_proto_goTypes = []any{
	(*GetDataplaneRequest)(nil),    // 0: proto.GetDataplaneRequest
	(*GetDataplaneResponse)(nil),   // 1: proto.GetDataplaneResponse
	(*KokaqNamespaceRequest)(nil),  // 2: proto.KokaqNamespaceRequest
	(*KokaqQueueRequest)(nil),      // 3: proto.KokaqQueueRequest
	(*KokaqNamespaceResponse)(nil), // 4: proto.KokaqNamespaceResponse
	(*StatusResponse)(nil),         // 5: proto.StatusResponse
	(*KokaqQueueResponse)(nil),     // 6: proto.KokaqQueueResponse
	(*KokaqStatsResponse)(nil),     // 7: proto.KokaqStatsResponse
}
var file_proto_control_proto_depIdxs = []int32{
	0, // 0: proto.KokaqControlPlane.GetDataplane:input_type -> proto.GetDataplaneRequest
	2, // 1: proto.KokaqControlPlane.GetNamespace:input_type -> proto.KokaqNamespaceRequest
	2, // 2: proto.KokaqControlPlane.AddNamespace:input_type -> proto.KokaqNamespaceRequest
	2, // 3: proto.KokaqControlPlane.DeleteNamespace:input_type -> proto.KokaqNamespaceRequest
	3, // 4: proto.KokaqControlPlane.AddQueue:input_type -> proto.KokaqQueueRequest
	3, // 5: proto.KokaqControlPlane.GetQueue:input_type -> proto.KokaqQueueRequest
	3, // 6: proto.KokaqControlPlane.DeleteQueue:input_type -> proto.KokaqQueueRequest
	3, // 7: proto.KokaqControlPlane.ClearQueue:input_type -> proto.KokaqQueueRequest
	2, // 8: proto.KokaqControlPlane.GetStats:input_type -> proto.KokaqNamespaceRequest
	1, // 9: proto.KokaqControlPlane.GetDataplane:output_type -> proto.GetDataplaneResponse
	4, // 10: proto.KokaqControlPlane.GetNamespace:output_type -> proto.KokaqNamespaceResponse
	4, // 11: proto.KokaqControlPlane.AddNamespace:output_type -> proto.KokaqNamespaceResponse
	5, // 12: proto.KokaqControlPlane.DeleteNamespace:output_type -> proto.StatusResponse
	6, // 13: proto.KokaqControlPlane.AddQueue:output_type -> proto.KokaqQueueResponse
	6, // 14: proto.KokaqControlPlane.GetQueue:output_type -> proto.KokaqQueueResponse
	5, // 15: proto.KokaqControlPlane.DeleteQueue:output_type -> proto.StatusResponse
	5, // 16: proto.KokaqControlPlane.ClearQueue:output_type -> proto.StatusResponse
	7, // 17: proto.KokaqControlPlane.GetStats:output_type -> proto.KokaqStatsResponse
	9, // [9:18] is the sub-list for method output_type
	0, // [0:9] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_control_proto_init() }
func file_proto_control_proto_init() {
	if File_proto_control_proto != nil {
		return
	}
	file_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_control_proto_rawDesc), len(file_proto_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_control_proto_goTypes,
		DependencyIndexes: file_proto_control_proto_depIdxs,
		MessageInfos:      file_proto_control_proto_msgTypes,
	}.Build()
	File_proto_control_proto = out.File
	file_proto_control_proto_goTypes = nil
	file_proto_control_proto_depIdxs = nil
}
