// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/data.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KokaqMessageHeaders struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentType   string                 `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	FailureReason FailureReason          `protobuf:"varint,4,opt,name=failure_reason,json=failureReason,proto3,enum=proto.FailureReason" json:"failure_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KokaqMessageHeaders) Reset() {
	*x = KokaqMessageHeaders{}
	mi := &file_proto_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KokaqMessageHeaders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KokaqMessageHeaders) ProtoMessage() {}

func (x *KokaqMessageHeaders) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KokaqMessageHeaders.ProtoReflect.Descriptor instead.
func (*KokaqMessageHeaders) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{0}
}

func (x *KokaqMessageHeaders) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *KokaqMessageHeaders) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *KokaqMessageHeaders) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *KokaqMessageHeaders) GetFailureReason() FailureReason {
	if x != nil {
		return x.FailureReason
	}
	return FailureReason_MESSAGE_FAILURE_UNSPECIFIED
}

type KokaqMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Queue         string                 `protobuf:"bytes,3,opt,name=queue,proto3" json:"queue,omitempty"`
	Priority      uint64                 `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Headers       *KokaqMessageHeaders   `protobuf:"bytes,6,opt,name=headers,proto3" json:"headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KokaqMessageRequest) Reset() {
	*x = KokaqMessageRequest{}
	mi := &file_proto_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KokaqMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KokaqMessageRequest) ProtoMessage() {}

func (x *KokaqMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KokaqMessageRequest.ProtoReflect.Descriptor instead.
func (*KokaqMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{1}
}

func (x *KokaqMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *KokaqMessageRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *KokaqMessageRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *KokaqMessageRequest) GetPriority() uint64 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *KokaqMessageRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *KokaqMessageRequest) GetHeaders() *KokaqMessageHeaders {
	if x != nil {
		return x.Headers
	}
	return nil
}

type KokaqMessageResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Message           *KokaqMessageRequest   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	CreatedOn         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_on,json=createdOn,proto3" json:"created_on,omitempty"`
	LastDequeued      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_dequeued,json=lastDequeued,proto3" json:"last_dequeued,omitempty"`
	Expiry            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expiry,proto3" json:"expiry,omitempty"`
	DeadLetteredAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=dead_lettered_at,json=deadLetteredAt,proto3" json:"dead_lettered_at,omitempty"`
	VisibilityTimeout uint32                 `protobuf:"varint,6,opt,name=visibility_timeout,json=visibilityTimeout,proto3" json:"visibility_timeout,omitempty"`
	RetryCount        uint32                 `protobuf:"varint,7,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *KokaqMessageResponse) Reset() {
	*x = KokaqMessageResponse{}
	mi := &file_proto_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KokaqMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KokaqMessageResponse) ProtoMessage() {}

func (x *KokaqMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KokaqMessageResponse.ProtoReflect.Descriptor instead.
func (*KokaqMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{2}
}

func (x *KokaqMessageResponse) GetMessage() *KokaqMessageRequest {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *KokaqMessageResponse) GetCreatedOn() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedOn
	}
	return nil
}

func (x *KokaqMessageResponse) GetLastDequeued() *timestamppb.Timestamp {
	if x != nil {
		return x.LastDequeued
	}
	return nil
}

func (x *KokaqMessageResponse) GetExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiry
	}
	return nil
}

func (x *KokaqMessageResponse) GetDeadLetteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeadLetteredAt
	}
	return nil
}

func (x *KokaqMessageResponse) GetVisibilityTimeout() uint32 {
	if x != nil {
		return x.VisibilityTimeout
	}
	return 0
}

func (x *KokaqMessageResponse) GetRetryCount() uint32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

type EnqueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *KokaqMessageRequest   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueRequest) Reset() {
	*x = EnqueueRequest{}
	mi := &file_proto_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueRequest) ProtoMessage() {}

func (x *EnqueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueRequest.ProtoReflect.Descriptor instead.
func (*EnqueueRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{3}
}

func (x *EnqueueRequest) GetMessage() *KokaqMessageRequest {
	if x != nil {
		return x.Message
	}
	return nil
}

type EnqueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	EnqueuedAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=enqueued_at,json=enqueuedAt,proto3" json:"enqueued_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueResponse) Reset() {
	*x = EnqueueResponse{}
	mi := &file_proto_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueResponse) ProtoMessage() {}

func (x *EnqueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueResponse.ProtoReflect.Descriptor instead.
func (*EnqueueResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{4}
}

func (x *EnqueueResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *EnqueueResponse) GetEnqueuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EnqueuedAt
	}
	return nil
}

type DequeueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Queue         string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	MaxCount      uint32                 `protobuf:"varint,3,opt,name=max_count,json=maxCount,proto3" json:"max_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DequeueRequest) Reset() {
	*x = DequeueRequest{}
	mi := &file_proto_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DequeueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DequeueRequest) ProtoMessage() {}

func (x *DequeueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DequeueRequest.ProtoReflect.Descriptor instead.
func (*DequeueRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{5}
}

func (x *DequeueRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DequeueRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *DequeueRequest) GetMaxCount() uint32 {
	if x != nil {
		return x.MaxCount
	}
	return 0
}

type DequeueResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Messages      []*KokaqMessageResponse `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DequeueResponse) Reset() {
	*x = DequeueResponse{}
	mi := &file_proto_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DequeueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DequeueResponse) ProtoMessage() {}

func (x *DequeueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DequeueResponse.ProtoReflect.Descriptor instead.
func (*DequeueResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{6}
}

func (x *DequeueResponse) GetMessages() []*KokaqMessageResponse {
	if x != nil {
		return x.Messages
	}
	return nil
}

// Peek messages without locking
type PeekRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Queue         string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	Count         uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeekRequest) Reset() {
	*x = PeekRequest{}
	mi := &file_proto_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeekRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeekRequest) ProtoMessage() {}

func (x *PeekRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeekRequest.ProtoReflect.Descriptor instead.
func (*PeekRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{7}
}

func (x *PeekRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PeekRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *PeekRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type PeekResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Messages      []*KokaqMessageResponse `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeekResponse) Reset() {
	*x = PeekResponse{}
	mi := &file_proto_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeekResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeekResponse) ProtoMessage() {}

func (x *PeekResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeekResponse.ProtoReflect.Descriptor instead.
func (*PeekResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{8}
}

func (x *PeekResponse) GetMessages() []*KokaqMessageResponse {
	if x != nil {
		return x.Messages
	}
	return nil
}

// PeekLock - acquire locks on messages
type PeekLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Queue         string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	MessageId     string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	LockDuration  uint32                 `protobuf:"varint,4,opt,name=lock_duration,json=lockDuration,proto3" json:"lock_duration,omitempty"` // in seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeekLockRequest) Reset() {
	*x = PeekLockRequest{}
	mi := &file_proto_data_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeekLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeekLockRequest) ProtoMessage() {}

func (x *PeekLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeekLockRequest.ProtoReflect.Descriptor instead.
func (*PeekLockRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{9}
}

func (x *PeekLockRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PeekLockRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *PeekLockRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *PeekLockRequest) GetLockDuration() uint32 {
	if x != nil {
		return x.LockDuration
	}
	return 0
}

type LockedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *KokaqMessageResponse  `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	LockId        string                 `protobuf:"bytes,2,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	LockExpiresAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=lock_expires_at,json=lockExpiresAt,proto3" json:"lock_expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockedMessage) Reset() {
	*x = LockedMessage{}
	mi := &file_proto_data_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockedMessage) ProtoMessage() {}

func (x *LockedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockedMessage.ProtoReflect.Descriptor instead.
func (*LockedMessage) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{10}
}

func (x *LockedMessage) GetMessage() *KokaqMessageResponse {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *LockedMessage) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

func (x *LockedMessage) GetLockExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LockExpiresAt
	}
	return nil
}

type PeekLockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locked        []*LockedMessage       `protobuf:"bytes,1,rep,name=locked,proto3" json:"locked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeekLockResponse) Reset() {
	*x = PeekLockResponse{}
	mi := &file_proto_data_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeekLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeekLockResponse) ProtoMessage() {}

func (x *PeekLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeekLockResponse.ProtoReflect.Descriptor instead.
func (*PeekLockResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{11}
}

func (x *PeekLockResponse) GetLocked() []*LockedMessage {
	if x != nil {
		return x.Locked
	}
	return nil
}

// Acknowledge message processing
type AckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Queue         string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	MessageId     string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	LockId        string                 `protobuf:"bytes,4,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_proto_data_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{12}
}

func (x *AckRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AckRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *AckRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *AckRequest) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

type AckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"` // optional: google.protobuf.Timestamp deleted_at = 2;
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_proto_data_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{13}
}

func (x *AckResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

// Negative acknowledgement
type NackRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Namespace          string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Queue              string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	MessageId          string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	LockId             string                 `protobuf:"bytes,4,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	FailureReason      FailureReason          `protobuf:"varint,5,opt,name=failure_reason,json=failureReason,proto3,enum=proto.FailureReason" json:"failure_reason,omitempty"`
	RequeueImmediately bool                   `protobuf:"varint,6,opt,name=requeue_immediately,json=requeueImmediately,proto3" json:"requeue_immediately,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NackRequest) Reset() {
	*x = NackRequest{}
	mi := &file_proto_data_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NackRequest) ProtoMessage() {}

func (x *NackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NackRequest.ProtoReflect.Descriptor instead.
func (*NackRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{14}
}

func (x *NackRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *NackRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *NackRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *NackRequest) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

func (x *NackRequest) GetFailureReason() FailureReason {
	if x != nil {
		return x.FailureReason
	}
	return FailureReason_MESSAGE_FAILURE_UNSPECIFIED
}

func (x *NackRequest) GetRequeueImmediately() bool {
	if x != nil {
		return x.RequeueImmediately
	}
	return false
}

type NackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeadLettered  bool                   `protobuf:"varint,1,opt,name=dead_lettered,json=deadLettered,proto3" json:"dead_lettered,omitempty"`
	Requeued      bool                   `protobuf:"varint,2,opt,name=requeued,proto3" json:"requeued,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NackResponse) Reset() {
	*x = NackResponse{}
	mi := &file_proto_data_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NackResponse) ProtoMessage() {}

func (x *NackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NackResponse.ProtoReflect.Descriptor instead.
func (*NackResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{15}
}

func (x *NackResponse) GetDeadLettered() bool {
	if x != nil {
		return x.DeadLettered
	}
	return false
}

func (x *NackResponse) GetRequeued() bool {
	if x != nil {
		return x.Requeued
	}
	return false
}

// Release lock explicitly
type ReleaseLockRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Namespace      string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Queue          string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	MessageId      string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	LockId         string                 `protobuf:"bytes,4,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	MakeVisibleNow bool                   `protobuf:"varint,5,opt,name=make_visible_now,json=makeVisibleNow,proto3" json:"make_visible_now,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReleaseLockRequest) Reset() {
	*x = ReleaseLockRequest{}
	mi := &file_proto_data_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseLockRequest) ProtoMessage() {}

func (x *ReleaseLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseLockRequest.ProtoReflect.Descriptor instead.
func (*ReleaseLockRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{16}
}

func (x *ReleaseLockRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ReleaseLockRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *ReleaseLockRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ReleaseLockRequest) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

func (x *ReleaseLockRequest) GetMakeVisibleNow() bool {
	if x != nil {
		return x.MakeVisibleNow
	}
	return false
}

type ReleaseLockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Released      bool                   `protobuf:"varint,1,opt,name=released,proto3" json:"released,omitempty"`
	VisibleAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=visible_at,json=visibleAt,proto3" json:"visible_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseLockResponse) Reset() {
	*x = ReleaseLockResponse{}
	mi := &file_proto_data_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseLockResponse) ProtoMessage() {}

func (x *ReleaseLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseLockResponse.ProtoReflect.Descriptor instead.
func (*ReleaseLockResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{17}
}

func (x *ReleaseLockResponse) GetReleased() bool {
	if x != nil {
		return x.Released
	}
	return false
}

func (x *ReleaseLockResponse) GetVisibleAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VisibleAt
	}
	return nil
}

// Extend lock visibility timeout
type ExtendVisibilityTimeoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Queue         string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	MessageId     string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	AdditionalMs  uint32                 `protobuf:"varint,4,opt,name=additional_ms,json=additionalMs,proto3" json:"additional_ms,omitempty"`
	LockId        string                 `protobuf:"bytes,5,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendVisibilityTimeoutRequest) Reset() {
	*x = ExtendVisibilityTimeoutRequest{}
	mi := &file_proto_data_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendVisibilityTimeoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendVisibilityTimeoutRequest) ProtoMessage() {}

func (x *ExtendVisibilityTimeoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendVisibilityTimeoutRequest.ProtoReflect.Descriptor instead.
func (*ExtendVisibilityTimeoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{18}
}

func (x *ExtendVisibilityTimeoutRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ExtendVisibilityTimeoutRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *ExtendVisibilityTimeoutRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ExtendVisibilityTimeoutRequest) GetAdditionalMs() uint32 {
	if x != nil {
		return x.AdditionalMs
	}
	return 0
}

func (x *ExtendVisibilityTimeoutRequest) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

// Refresh (keep-alive) current timeout
type RefreshVisibilityTimeoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Queue         string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	MessageId     string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	LockId        string                 `protobuf:"bytes,4,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshVisibilityTimeoutRequest) Reset() {
	*x = RefreshVisibilityTimeoutRequest{}
	mi := &file_proto_data_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshVisibilityTimeoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshVisibilityTimeoutRequest) ProtoMessage() {}

func (x *RefreshVisibilityTimeoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshVisibilityTimeoutRequest.ProtoReflect.Descriptor instead.
func (*RefreshVisibilityTimeoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{19}
}

func (x *RefreshVisibilityTimeoutRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RefreshVisibilityTimeoutRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *RefreshVisibilityTimeoutRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *RefreshVisibilityTimeoutRequest) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

// Override timeout
type SetVisibilityTimeoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Queue         string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	MessageId     string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	NewTimeoutMs  uint32                 `protobuf:"varint,4,opt,name=new_timeout_ms,json=newTimeoutMs,proto3" json:"new_timeout_ms,omitempty"`
	LockId        string                 `protobuf:"bytes,5,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVisibilityTimeoutRequest) Reset() {
	*x = SetVisibilityTimeoutRequest{}
	mi := &file_proto_data_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVisibilityTimeoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVisibilityTimeoutRequest) ProtoMessage() {}

func (x *SetVisibilityTimeoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVisibilityTimeoutRequest.ProtoReflect.Descriptor instead.
func (*SetVisibilityTimeoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{20}
}

func (x *SetVisibilityTimeoutRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SetVisibilityTimeoutRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *SetVisibilityTimeoutRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SetVisibilityTimeoutRequest) GetNewTimeoutMs() uint32 {
	if x != nil {
		return x.NewTimeoutMs
	}
	return 0
}

func (x *SetVisibilityTimeoutRequest) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

type VisibilityTimeoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockExpiresAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=lock_expires_at,json=lockExpiresAt,proto3" json:"lock_expires_at,omitempty"`
	Applied       bool                   `protobuf:"varint,2,opt,name=applied,proto3" json:"applied,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisibilityTimeoutResponse) Reset() {
	*x = VisibilityTimeoutResponse{}
	mi := &file_proto_data_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisibilityTimeoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisibilityTimeoutResponse) ProtoMessage() {}

func (x *VisibilityTimeoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisibilityTimeoutResponse.ProtoReflect.Descriptor instead.
func (*VisibilityTimeoutResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{21}
}

func (x *VisibilityTimeoutResponse) GetLockExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LockExpiresAt
	}
	return nil
}

func (x *VisibilityTimeoutResponse) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

type KokaqNewQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *KokaqQueueRequest     `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	ShardId       uint64                 `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KokaqNewQueueRequest) Reset() {
	*x = KokaqNewQueueRequest{}
	mi := &file_proto_data_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KokaqNewQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KokaqNewQueueRequest) ProtoMessage() {}

func (x *KokaqNewQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KokaqNewQueueRequest.ProtoReflect.Descriptor instead.
func (*KokaqNewQueueRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{22}
}

func (x *KokaqNewQueueRequest) GetRequest() *KokaqQueueRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *KokaqNewQueueRequest) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

var File_proto_data_proto protoreflect.FileDescriptor

const file_proto_data_proto_rawDesc = "" +
	"\n" +
	"\x10proto/data.proto\x12\x05proto\x1a\x12proto/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb4\x01\n" +
	"\x13KokaqMessageHeaders\x12!\n" +
	"\fcontent_type\x18\x01 \x01(\tR\vcontentType\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12;\n" +
	"\x0efailure_reason\x18\x04 \x01(\x0e2\x14.proto.FailureReasonR\rfailureReason\"\xd4\x01\n" +
	"\x13KokaqMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05queue\x18\x03 \x01(\tR\x05queue\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x04R\bpriority\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x124\n" +
	"\aheaders\x18\x06 \x01(\v2\x1a.proto.KokaqMessageHeadersR\aheaders\"\x92\x03\n" +
	"\x14KokaqMessageResponse\x124\n" +
	"\amessage\x18\x01 \x01(\v2\x1a.proto.KokaqMessageRequestR\amessage\x129\n" +
	"\n" +
	"created_on\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedOn\x12?\n" +
	"\rlast_dequeued\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\flastDequeued\x122\n" +
	"\x06expiry\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x06expiry\x12D\n" +
	"\x10dead_lettered_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0edeadLetteredAt\x12-\n" +
	"\x12visibility_timeout\x18\x06 \x01(\rR\x11visibilityTimeout\x12\x1f\n" +
	"\vretry_count\x18\a \x01(\rR\n" +
	"retryCount\"F\n" +
	"\x0eEnqueueRequest\x124\n" +
	"\amessage\x18\x01 \x01(\v2\x1a.proto.KokaqMessageRequestR\amessage\"m\n" +
	"\x0fEnqueueResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12;\n" +
	"\venqueued_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"enqueuedAt\"a\n" +
	"\x0eDequeueRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x1b\n" +
	"\tmax_count\x18\x03 \x01(\rR\bmaxCount\"J\n" +
	"\x0fDequeueResponse\x127\n" +
	"\bmessages\x18\x01 \x03(\v2\x1b.proto.KokaqMessageResponseR\bmessages\"W\n" +
	"\vPeekRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\"G\n" +
	"\fPeekResponse\x127\n" +
	"\bmessages\x18\x01 \x03(\v2\x1b.proto.KokaqMessageResponseR\bmessages\"\x89\x01\n" +
	"\x0fPeekLockRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12#\n" +
	"\rlock_duration\x18\x04 \x01(\rR\flockDuration\"\xa3\x01\n" +
	"\rLockedMessage\x125\n" +
	"\amessage\x18\x01 \x01(\v2\x1b.proto.KokaqMessageResponseR\amessage\x12\x17\n" +
	"\alock_id\x18\x02 \x01(\tR\x06lockId\x12B\n" +
	"\x0flock_expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rlockExpiresAt\"@\n" +
	"\x10PeekLockResponse\x12,\n" +
	"\x06locked\x18\x01 \x03(\v2\x14.proto.LockedMessageR\x06locked\"x\n" +
	"\n" +
	"AckRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12\x17\n" +
	"\alock_id\x18\x04 \x01(\tR\x06lockId\"1\n" +
	"\vAckResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"\xe7\x01\n" +
	"\vNackRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12\x17\n" +
	"\alock_id\x18\x04 \x01(\tR\x06lockId\x12;\n" +
	"\x0efailure_reason\x18\x05 \x01(\x0e2\x14.proto.FailureReasonR\rfailureReason\x12/\n" +
	"\x13requeue_immediately\x18\x06 \x01(\bR\x12requeueImmediately\"O\n" +
	"\fNackResponse\x12#\n" +
	"\rdead_lettered\x18\x01 \x01(\bR\fdeadLettered\x12\x1a\n" +
	"\brequeued\x18\x02 \x01(\bR\brequeued\"\xaa\x01\n" +
	"\x12ReleaseLockRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12\x17\n" +
	"\alock_id\x18\x04 \x01(\tR\x06lockId\x12(\n" +
	"\x10make_visible_now\x18\x05 \x01(\bR\x0emakeVisibleNow\"l\n" +
	"\x13ReleaseLockResponse\x12\x1a\n" +
	"\breleased\x18\x01 \x01(\bR\breleased\x129\n" +
	"\n" +
	"visible_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tvisibleAt\"\xb1\x01\n" +
	"\x1eExtendVisibilityTimeoutRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12#\n" +
	"\radditional_ms\x18\x04 \x01(\rR\fadditionalMs\x12\x17\n" +
	"\alock_id\x18\x05 \x01(\tR\x06lockId\"\x8d\x01\n" +
	"\x1fRefreshVisibilityTimeoutRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12\x17\n" +
	"\alock_id\x18\x04 \x01(\tR\x06lockId\"\xaf\x01\n" +
	"\x1bSetVisibilityTimeoutRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12$\n" +
	"\x0enew_timeout_ms\x18\x04 \x01(\rR\fnewTimeoutMs\x12\x17\n" +
	"\alock_id\x18\x05 \x01(\tR\x06lockId\"y\n" +
	"\x19VisibilityTimeoutResponse\x12B\n" +
	"\x0flock_expires_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\rlockExpiresAt\x12\x18\n" +
	"\aapplied\x18\x02 \x01(\bR\aapplied\"e\n" +
	"\x14KokaqNewQueueRequest\x122\n" +
	"\arequest\x18\x01 \x01(\v2\x18.proto.KokaqQueueRequestR\arequest\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\x04R\ashardId2\xdf\a\n" +
	"\x0eKokaqDataPlane\x12=\n" +
	"\x03New\x12\x1b.proto.KokaqNewQueueRequest\x1a\x19.proto.KokaqQueueResponse\x12:\n" +
	"\x03Get\x12\x18.proto.KokaqQueueRequest\x1a\x19.proto.KokaqQueueResponse\x12?\n" +
	"\bGetStats\x12\x18.proto.KokaqQueueRequest\x1a\x19.proto.KokaqStatsResponse\x129\n" +
	"\x06Delete\x12\x18.proto.KokaqQueueRequest\x1a\x15.proto.StatusResponse\x128\n" +
	"\x05Clear\x12\x18.proto.KokaqQueueRequest\x1a\x15.proto.StatusResponse\x128\n" +
	"\aEnqueue\x12\x15.proto.EnqueueRequest\x1a\x16.proto.EnqueueResponse\x128\n" +
	"\aDequeue\x12\x15.proto.DequeueRequest\x1a\x16.proto.DequeueResponse\x12/\n" +
	"\x04Peek\x12\x12.proto.PeekRequest\x1a\x13.proto.PeekResponse\x12;\n" +
	"\bPeekLock\x12\x16.proto.PeekLockRequest\x1a\x17.proto.PeekLockResponse\x12,\n" +
	"\x03Ack\x12\x11.proto.AckRequest\x1a\x12.proto.AckResponse\x12/\n" +
	"\x04Nack\x12\x12.proto.NackRequest\x1a\x13.proto.NackResponse\x12Q\n" +
	"\x06Extend\x12%.proto.ExtendVisibilityTimeoutRequest\x1a .proto.VisibilityTimeoutResponse\x12\\\n" +
	"\x14SetVisibilityTimeout\x12\".proto.SetVisibilityTimeoutRequest\x1a .proto.VisibilityTimeoutResponse\x12d\n" +
	"\x18RefreshVisibilityTimeout\x12&.proto.RefreshVisibilityTimeoutRequest\x1a .proto.VisibilityTimeoutResponse\x12D\n" +
	"\vReleaseLock\x12\x19.proto.ReleaseLockRequest\x1a\x1a.proto.ReleaseLockResponseB!Z\x1fgithub.com/kokaq/protocol/protob\x06proto3"

var (
	file_proto_data_proto_rawDescOnce sync.Once
	file_proto_data_proto_rawDescData []byte
)

func file_proto_data_proto_rawDescGZIP() []byte {
	file_proto_data_proto_rawDescOnce.Do(func() {
		file_proto_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_data_proto_rawDesc), len(file_proto_data_proto_rawDesc)))
	})
	return file_proto_data_proto_rawDescData
}

var file_proto_data_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_data_proto_goTypes = []any{
	(*KokaqMessageHeaders)(nil),             // 0: proto.KokaqMessageHeaders
	(*KokaqMessageRequest)(nil),             // 1: proto.KokaqMessageRequest
	(*KokaqMessageResponse)(nil),            // 2: proto.KokaqMessageResponse
	(*EnqueueRequest)(nil),                  // 3: proto.EnqueueRequest
	(*EnqueueResponse)(nil),                 // 4: proto.EnqueueResponse
	(*DequeueRequest)(nil),                  // 5: proto.DequeueRequest
	(*DequeueResponse)(nil),                 // 6: proto.DequeueResponse
	(*PeekRequest)(nil),                     // 7: proto.PeekRequest
	(*PeekResponse)(nil),                    // 8: proto.PeekResponse
	(*PeekLockRequest)(nil),                 // 9: proto.PeekLockRequest
	(*LockedMessage)(nil),                   // 10: proto.LockedMessage
	(*PeekLockResponse)(nil),                // 11: proto.PeekLockResponse
	(*AckRequest)(nil),                      // 12: proto.AckRequest
	(*AckResponse)(nil),                     // 13: proto.AckResponse
	(*NackRequest)(nil),                     // 14: proto.NackRequest
	(*NackResponse)(nil),                    // 15: proto.NackResponse
	(*ReleaseLockRequest)(nil),              // 16: proto.ReleaseLockRequest
	(*ReleaseLockResponse)(nil),             // 17: proto.ReleaseLockResponse
	(*ExtendVisibilityTimeoutRequest)(nil),  // 18: proto.ExtendVisibilityTimeoutRequest
	(*RefreshVisibilityTimeoutRequest)(nil), // 19: proto.RefreshVisibilityTimeoutRequest
	(*SetVisibilityTimeoutRequest)(nil),     // 20: proto.SetVisibilityTimeoutRequest
	(*VisibilityTimeoutResponse)(nil),       // 21: proto.VisibilityTimeoutResponse
	(*KokaqNewQueueRequest)(nil),            // 22: proto.KokaqNewQueueRequest
	(FailureReason)(0),                      // 23: proto.FailureReason
	(*timestamppb.Timestamp)(nil),           // 24: google.protobuf.Timestamp
	(*KokaqQueueRequest)(nil),               // 25: proto.KokaqQueueRequest
	(*KokaqQueueResponse)(nil),              // 26: proto.KokaqQueueResponse
	(*KokaqStatsResponse)(nil),              // 27: proto.KokaqStatsResponse
	(*StatusResponse)(nil),                  // 28: proto.StatusResponse
}
var file_proto_data_proto_depIdxs = []int32{
	23, // 0: proto.KokaqMessageHeaders.failure_reason:type_name -> proto.FailureReason
	0,  // 1: proto.KokaqMessageRequest.headers:type_name -> proto.KokaqMessageHeaders
	1,  // 2: proto.KokaqMessageResponse.message:type_name -> proto.KokaqMessageRequest
	24, // 3: proto.KokaqMessageResponse.created_on:type_name -> google.protobuf.Timestamp
	24, // 4: proto.KokaqMessageResponse.last_dequeued:type_name -> google.protobuf.Timestamp
	24, // 5: proto.KokaqMessageResponse.expiry:type_name -> google.protobuf.Timestamp
	24, // 6: proto.KokaqMessageResponse.dead_lettered_at:type_name -> google.protobuf.Timestamp
	1,  // 7: proto.EnqueueRequest.message:type_name -> proto.KokaqMessageRequest
	24, // 8: proto.EnqueueResponse.enqueued_at:type_name -> google.protobuf.Timestamp
	2,  // 9: proto.DequeueResponse.messages:type_name -> proto.KokaqMessageResponse
	2,  // 10: proto.PeekResponse.messages:type_name -> proto.KokaqMessageResponse
	2,  // 11: proto.LockedMessage.message:type_name -> proto.KokaqMessageResponse
	24, // 12: proto.LockedMessage.lock_expires_at:type_name -> google.protobuf.Timestamp
	10, // 13: proto.PeekLockResponse.locked:type_name -> proto.LockedMessage
	23, // 14: proto.NackRequest.failure_reason:type_name -> proto.FailureReason
	24, // 15: proto.ReleaseLockResponse.visible_at:type_name -> google.protobuf.Timestamp
	24, // 16: proto.VisibilityTimeoutResponse.lock_expires_at:type_name -> google.protobuf.Timestamp
	25, // 17: proto.KokaqNewQueueRequest.request:type_name -> proto.KokaqQueueRequest
	22, // 18: proto.KokaqDataPlane.New:input_type -> proto.KokaqNewQueueRequest
	25, // 19: proto.KokaqDataPlane.Get:input_type -> proto.KokaqQueueRequest
	25, // 20: proto.KokaqDataPlane.GetStats:input_type -> proto.KokaqQueueRequest
	25, // 21: proto.KokaqDataPlane.Delete:input_type -> proto.KokaqQueueRequest
	25, // 22: proto.KokaqDataPlane.Clear:input_type -> proto.KokaqQueueRequest
	3,  // 23: proto.KokaqDataPlane.Enqueue:input_type -> proto.EnqueueRequest
	5,  // 24: proto.KokaqDataPlane.Dequeue:input_type -> proto.DequeueRequest
	7,  // 25: proto.KokaqDataPlane.Peek:input_type -> proto.PeekRequest
	9,  // 26: proto.KokaqDataPlane.PeekLock:input_type -> proto.PeekLockRequest
	12, // 27: proto.KokaqDataPlane.Ack:input_type -> proto.AckRequest
	14, // 28: proto.KokaqDataPlane.Nack:input_type -> proto.NackRequest
	18, // 29: proto.KokaqDataPlane.Extend:input_type -> proto.ExtendVisibilityTimeoutRequest
	20, // 30: proto.KokaqDataPlane.SetVisibilityTimeout:input_type -> proto.SetVisibilityTimeoutRequest
	19, // 31: proto.KokaqDataPlane.RefreshVisibilityTimeout:input_type -> proto.RefreshVisibilityTimeoutRequest
	16, // 32: proto.KokaqDataPlane.ReleaseLock:input_type -> proto.ReleaseLockRequest
	26, // 33: proto.KokaqDataPlane.New:output_type -> proto.KokaqQueueResponse
	26, // 34: proto.KokaqDataPlane.Get:output_type -> proto.KokaqQueueResponse
	27, // 35: proto.KokaqDataPlane.GetStats:output_type -> proto.KokaqStatsResponse
	28, // 36: proto.KokaqDataPlane.Delete:output_type -> proto.StatusResponse
	28, // 37: proto.KokaqDataPlane.Clear:output_type -> proto.StatusResponse
	4,  // 38: proto.KokaqDataPlane.Enqueue:output_type -> proto.EnqueueResponse
	6,  // 39: proto.KokaqDataPlane.Dequeue:output_type -> proto.DequeueResponse
	8,  // 40: proto.KokaqDataPlane.Peek:output_type -> proto.PeekResponse
	11, // 41: proto.KokaqDataPlane.PeekLock:output_type -> proto.PeekLockResponse
	13, // 42: proto.KokaqDataPlane.Ack:output_type -> proto.AckResponse
	15, // 43: proto.KokaqDataPlane.Nack:output_type -> proto.NackResponse
	21, // 44: proto.KokaqDataPlane.Extend:output_type -> proto.VisibilityTimeoutResponse
	21, // 45: proto.KokaqDataPlane.SetVisibilityTimeout:output_type -> proto.VisibilityTimeoutResponse
	21, // 46: proto.KokaqDataPlane.RefreshVisibilityTimeout:output_type -> proto.VisibilityTimeoutResponse
	17, // 47: proto.KokaqDataPlane.ReleaseLock:output_type -> proto.ReleaseLockResponse
	33, // [33:48] is the sub-list for method output_type
	18, // [18:33] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_data_proto_init() }
func file_proto_data_proto_init() {
	if File_proto_data_proto != nil {
		return
	}
	file_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_data_proto_rawDesc), len(file_proto_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_data_proto_goTypes,
		DependencyIndexes: file_proto_data_proto_depIdxs,
		MessageInfos:      file_proto_data_proto_msgTypes,
	}.Build()
	File_proto_data_proto = out.File
	file_proto_data_proto_goTypes = nil
	file_proto_data_proto_depIdxs = nil
}
